title: "Kamal"
description: "Deploy web apps anywhere"
url: https://kamal-deploy.org
image: /assets/images/opengraph.png
github: basecamp
repository: basecamp/kamal-site
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-redirect-from

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: docs
      type: pages
    values:
      layout: docs
      search: true
  - scope:
      path: v1
      type: pages
    values:
      layout: default_v1
      search: true
  - scope:
      path: v1/docs
      type: pages
    values:
      layout: docs_v1
      search: true

redirect_from:
  json: false
